image: "debian/stable"
arch: "amd64"
shell: false
sources:
  - "https://git.sr.ht/~paxswill/mlx9064x"
tasks:
  - install_rustup: |
      curl \
        --proto '=https' \
        --tlsv1.2 \
        --silent \
        --show-error \
        --fail \
        --location \
        --output rustup-init \
        https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
      chmod +x ./rustup-init
      ./rustup-init \
        --profile minimal \
        --quiet \
        -y
      source $HOME/.cargo/env
      rustup component add clippy
      rustup component add rustfmt
  - check_nono: |
      source $HOME/.cargo/env
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-nono
      cd mlx9064x
      cargo nono check --project mlx9064x --no-default-features
  - test: |
      cd mlx9064x
      source $HOME/.cargo/env
      # Test with and without std
      cargo test
      cargo test --project mlx9064x --no-default-features --features libm
  - test-docs: |
      cd mlx9064x
      source $HOME/.cargo/env
      # Ensure all doc comments are well formed (even private ones)
      cargo rustdoc --project mlx9064x -- \
        --document-private-items \
        --deny rustdoc::broken_intra_doc_links \
        --deny rustdoc::private_intra_doc_links \
        --deny rustdoc::invalid_codeblock_attributes \
        --deny rustdoc::bare_urls
  - lints: |
      cd mlx9064x
      source $HOME/.cargo/env
      cargo clippy -- -D warnings
      cargo clippy --tests -- -D warnings
      cargo clippy --benches -- -D warnings
      cargo fmt -- --check
